name: ehr_db
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - python=3.7
  - numpy>=1.18.1
  - pandas>=1.0.1
  - pyarrow>=0.16.0
  - pip
  - plac>=1.0.0
  - pyscaffold
  - python-dotenv
  - tqdm
  - lz4
  - pyodbc>=4.0.30
  - psycopg2 >= 2.8.5
  - sqlalchemy >= 1.3.16
  - alembic >= 1.4.2
  - sqlalchemy-utils >= 0.36.3
  - jupyterlab>=2.0.1       # for developing things
  - ipywidgets>=7.5.1
  - nodejs                  # for ipywidgets in jupyterlab
